services:
  postgres:
    image: 'postgres:latest'
    env_file: # Load variables from this file into the container environment
      - local-conf.env
    environment:
      - POSTGRES_DB=pedal_pal_service_dev
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - '5432:5432'
